---
title: "LSA Errors"
author: "Genelle Denzin"
date: "March 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Data Quality Flags Summary

Following are all the different kinds of Data Quality Flags:

```{r}
library(readxl)
library(tidyverse)
library(gt)
flags <- read_xlsx("data/LSA.xlsx", 
                   sheet = 4, 
                   skip = 5,
                   col_types = "text")
flagvendor <- flags %>%
  group_by(PossiblyVendorRelated) %>%
  summarise(Count = n())
flagdescriptions <- flags %>% 
  group_by(Category, FlagDescription, PossiblyVendorRelated, Type) %>% 
  summarise(Count = n()) %>%
  ungroup()
toptenflagtypes <- flagdescriptions %>% filter(Count > 30) 
gt(flagdescriptions %>% arrange(desc(flagdescriptions$Count)))

```

## How Much is Possibly Vendor Related

```{r}
ggplot(flagvendor %>% 
         select(PossiblyVendorRelated, Count),
       aes(PossiblyVendorRelated, Count)) + 
  geom_col()
```

## What Errors are Likely Mine?

```{r}
itsonme <- flagdescriptions %>% filter(PossiblyVendorRelated == "No")
gt(itsonme)
ggplot(flagdescriptions %>% 
         filter(PossiblyVendorRelated == "No") %>% 
         group_by(Type) %>%
         summarise(Count = n()), aes(Type, Count)) +
  geom_col()
```



```{r}
ggplot(flagdescriptions %>% 
         filter(PossiblyVendorRelated == "No") %>% 
         group_by(Category) %>%
         summarise(Count = n()), aes(Category, Count)) +
  geom_col() 
```


