---
title: "Unsheltered Entries"
author: "Genelle Denzin"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(here)
library(lubridate)
library(plotly)

load(here("images/cohorts.RData"))
load(here("images/COHHIOHMIS.RData"))

```

## New Entries into the Unsheltered Provider by County

```{r entries}

unsheltered_hhs <- co_clients_served %>%
  filter(ProjectName == "Unsheltered Clients - OUTREACH" &
           entered_between(., "09012019", ReportEnd)) %>%
  select(HouseholdID, EntryDate, ExitAdjust) %>%
  left_join(Enrollment %>% 
              select(HouseholdID, CountyServed, UserCreating),
            by = "HouseholdID") %>%
  unique()

# when the CountyServed field is null, we need to guess the County
county_guesses <- unsheltered_hhs %>%
  left_join(Users, by = "UserCreating")

counties <- regions$County
monthyears <- unsheltered_hhs %>%
  arrange(EntryDate) %>%
  mutate(EntryDateDisplay = format.Date(EntryDate, "%b %Y")) %>%
  pull(EntryDateDisplay) %>%
  unique()

df <- county_guesses %>%
  mutate(
    County = if_else(is.na(CountyServed),
                     UserCounty,
                     CountyServed),
    EntryDateDisplay = format.Date(EntryDate, "%b %Y")
  ) %>%
  select(HouseholdID, EntryDateDisplay, County) %>%
  group_by(EntryDateDisplay, County) %>%
  summarise(Entries = n()) %>%
  ungroup() %>%
  mutate(
    Entries = as.numeric(Entries),
    EntryDateDisplay = factor(EntryDateDisplay, levels = c(monthyears)),
    County = factor(County, levels = c(counties))
  ) %>%
  pivot_wider(names_from = County, values_from = Entries)

df[is.na(df)] <- 0

df <- df %>%
  pivot_longer(cols = !all_of("EntryDateDisplay"), 
               names_to = "County", 
               values_to = "Entries")

plot_ly(df %>% 
          arrange(EntryDateDisplay, County) %>%
          group_by(County), 
        x = ~EntryDateDisplay, 
        y = ~Entries, 
        type = 'scatter', 
        mode = 'lines', 
        color = ~County,
        colors = colorRampPalette(c("black",
                                    "purple",
                                    "blue",
                                    "green"))(80)
        )
```



